apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-service-db-pvc
  namespace: my-services
spec:
  accessModes:
    - ReadWriteOnce            # only one Pod may write at a time
  resources:
    requests:
      storage: 100Mi           # how much disk you need
  storageClassName: hostpath   # your clusterâ€™s default provisioner
